//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CorridorDBEntities : DbContext
    {
        public CorridorDBEntities()
            : base("name=CorridorDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {            
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Corridor> Corridors { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Staff_Corridor> Staff_Corridor { get; set; }
        public virtual DbSet<Staff_Task> Staff_Task { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
    }
}
