//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Task
    {
        public int id { get; set; }
        public Nullable<int> staffId { get; set; }
        public Nullable<int> taskId { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Task Task { get; set; }
    }
}
